---
eureka.client.serviceUrl.defaultZone=http://eureka-primary:8011/eureka,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
words: I,You,He,She,It,Test
server:
  port: ${PORT:${SERVER_PORT:0}}
